# Generated by Django 4.2 on 2025-01-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is2Fa',
            field=models.BooleanField(default=False),
        ),
    ]
