# Generated by Django 4.2 on 2025-01-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='game_type',
            field=models.CharField(max_length=20),
        ),
    ]
