# Generated by Django 4.2 on 2025-01-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_gamehistory_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='game_type',
            field=models.CharField(max_length=10),
        ),
    ]
