# Generated by Django 4.2 on 2025-01-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_gamehistory_game_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatistics',
            old_name='nombre_de_defaites',
            new_name='nb_defaites_1VS1',
        ),
        migrations.RenameField(
            model_name='userstatistics',
            old_name='nombre_de_parties',
            new_name='nb_defaites_2VS2',
        ),
        migrations.RenameField(
            model_name='userstatistics',
            old_name='nombre_de_tournois',
            new_name='nb_defaites_solo',
        ),
        migrations.RenameField(
            model_name='userstatistics',
            old_name='nombre_de_victoires_1vs1',
            new_name='nb_defaites_tournois',
        ),
        migrations.RenameField(
            model_name='userstatistics',
            old_name='nombre_de_victoires_tournoi',
            new_name='nb_parties_1VS1',
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='nb_parties_2VS2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='nb_parties_solo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='nb_tournois',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='nb_victoires_1VS1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='nb_victoires_2VS2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='nb_victoires_solo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='nb_victoires_tournois',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='GameHistory',
        ),
    ]
