# Generated by Django 4.2 on 2025-01-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_rename_nombre_de_defaites_userstatistics_nb_defaites_1vs1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatistics',
            old_name='nb_tournois',
            new_name='nb_parties_tournois',
        ),
    ]
