# Generated by Django 4.2 on 2025-01-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_nb_tournois_userstatistics_nb_parties_tournois'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
