# Generated by Django 4.2 on 2025-01-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_user_has_accepted_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_accepted_terms',
            field=models.BooleanField(default=True),
        ),
    ]
