# Generated by Django 4.2 on 2025-01-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/images/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
