# Generated by Django 4.2 on 2025-01-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
