
const dictionary = {
    en: {
    singlePlayer: "Single Player",
    multiPlayer: "Multi Player",
    isFourPlayer: "2 vs 2",
    start: "Start",
    restart: "Restart",
    settingsBtn: "Settings",
    offcanvasHeader: "Menu",
    statisticsBtn: "Statistics",
    tournamentBtn: "Tournament",
    historyBtn: "History",
    modalSettings: "Settings",
    ballHeader: "Ball",
    "speed-ball": "Speed",
    "acceleration-ball": "Acceleration",
    AI: "AI",
    "difficulty-ai": "Difficulty",
    language: "Language",
    "language-choice": "Choose Language",
    "validate-btn-Stgs": "Save changes",
    "input-Username": "Choose name for player",
    "input-Username-Finish": "All the players are named",
    "title-tournament": "Create Tournament",
    "input-username-btn": "Save",
    "start-tournament": "Start Tournament",
    loginModal: "Login",
    loginHeader: "Login",
    password: "Password",
    login: "Login",        
    "validate-btn-login": "Save Choices",
    "nbr-player-tournament": "Choose number of players",
    "defaultValue-nbrPlayer": "Default value is 4",
    "create-Tournament1": "Tournament",
    "2modal-BackBtn": "Back",
    "tournament-panel": "Tournament",
    "round-display": "Round",
    "order-playing": "Match Order",
    "winnerTournament": "The champion is ",
    "finishTournament" : "Finish",
    "registerHeader": "Register",
    "confpassword": "Confirm Password",
    "login-registe": "Username",
    "validate-btn-register": "Save Choices",
    "registerModalBtn": "Register",
    "textSize": "Size Text",
    "text-Size": "Choose Size",
    "sizes": "Small",
    "sizem": "Medium",
    "sizel": "Large",
    "sizexl": "Extra Large",
    "modalStatistics": "HISTORY",
    "modalStatistic": "HISTORY",
    "nbrPlayer-Btn" : "Next",
    "logoutModal" : "Logout",
    "profileModalLabel" : "PROFILE",
    "emailR" : "E-Mail",
    "login-change" : "Save changes",
    "regist-changes" : "Save changes",
    "stat-mode": "Mode",
    "stat-vict": "Victory",
    "stat-def": "Defeat",
    "stat-total": "Total",
    "stat-single": "Single Player",
    "stat-multi": "Multi Player",
    "stat-2v2": "2 v 2",
    "stat-tourn": "Tournament",
    "hist-mode": "Game Mode",
    "hist-date": "Date",
    "registerModalLabel": "REGISTER",
    "start-login": "Login",
    "start-password": "Password",
    "start-confpw": "Confirm Password",
    "start-mail": "E-mail",
    "register-save-btn": "Enter",
    "exampleModalLabel": "LOGIN",
    "login-start": "Login",
    "pw-start": "Password",
    "reset-password-link": "Forgot your password?",
    "validate-btn-login": "Enter",
    "command-ModalLabel" : "GAME CONTROLS",
    "gctrl-single" : "Single Player",
    "gctrl-splayer" : "Player",
    "gctrl-skey" : "Key",
    "gctrl-saction" : "Action",
    "gctrl-splayer1" : "Player 1",
    "gctrl-sw" : "W",
    "gctrl-swmoveup" : "Move Up",
    "gctrl-ss" : "S",
    "gctrl-smoveDown" : "Move Down",
    "gctrl-multi" : "Multi Player",
    "gctrl-mplayer" : "Player",
    "gctrl-mkey" : "Key",
    "gctrl-maction" : "Action",
    "gctrl-mplayer1" : "Player 1",
    "gctrl-mw" : "W",
    "gctrl-mwmoveup" : "Move Up",
    "gctrl-ms" : "S",
    "gctrl-mmoveDown" : "Move Down",
    "gctrl-mplayer2" : "Player 2",
    "gctrl-marrup" : "Arrow Up",
    "gctrl-mmoveup" : "Move Up",
    "gctrl-marrdown" : "Arrow Down",
    "gctrl-mmovedown" : "Move Down",
    "gctrl-2v2" : "2 vs 2",
    "gctrl-2team1" : "Team 1",
    "gctrl-2player" : "Player",
    "gctrl-2key" : "Key",
    "gctrl-2action" : "Action",
    "gctrl-2player1" : "Player 1",
    "gctrl-2w" : "W",
    "gctrl-2moveup" : "Move Up",
    "gctrl-2s" : "S",
    "gctrl-2movedown" : "Move Down",
    "gctrl-2player2" : "Player 2",
    "gctrl-2arrup" : "Arrow Up",
    "gctrl-2moveup2" : "Move Up",
    "gctrl-2arrdown" : "Arrow Down",
    "gctrl-2movedown2" : "Move Down",
    "gctrl-2team1" : "Team 2",
    "gctrl-2Tplayer" : "Player",
    "gctrl-2Tkey" : "Key",
    "gctrl-2Taction" : "Action",
    "gctrl-2Tplayer3" : "Player 3",
    "gctrl-2Tn" : "N",
    "gctrl-2Tmoveup" : "Move Up",
    "gctrl-2Tm" : "M",
    "gctrl-2Tmovedown" : "Move Down",
    "gctrl-2Tplayer4" : "Player 4",
    "gctrl-2T2" : "2",
    "gctrl-2Tmoveup2" : "Move Up",
    "gctrl-2T3" : "3",
    "gctrl-2Tmovedown2" : "Move Down",
    "gctrl-tournament" : "Tournament",
    "gctrl-tplayer" : "Player",
    "gctrl-tkey" : "Key",
    "gctrl-taction" : "Action",
    "gctrl-tplayer1" : "Player 1",
    "gctrl-tw" : "W",
    "gctrl-tmoveup2" : "Move Up",
    "gctrl-ts" : "S",
    "gctrl-tmovedown" : "Move Down",
    "gctrl-tplayer2" : "Player 2",
    "gctrl-tarrup" : "Arrow Up",
    "gctrl-tmoveup" : "Move Up",
    "gctrl-tarrdown2" : "Arrow Down",
    "gctrl-tmovedown2" : "Move Down",
    "enter-friend-name" : "Enter Name",
    "add-friend" : "Add Friend",
    "login-profile" : "Login",
    "friend-name" : "Friend Name",
    "online-stat" : "Online Status",
    "game-stat" : "Game Status",
    "save-changes-profile" : "Save Changes",
    "delete-profile" : "Delete Profile",
    "nbr-ball" : "Number",
    "hist-result" : "Result",
    "hist-time" : "Time",
    "general-conditions-link1" : "General Terms and Conditions",
    "general-conditions-link1" : "I agree to the terms and conditions",
    "codeInput" : "Enter the 6-digit code sent to your email",
    "twofactor" : "Two-Factors Authentification",
    "validate-otp-btn" : "Validate OTP",
    "otp-input" : "Enter your OTP", 
},
fr: {
    singlePlayer: "Joueur Unique",
    multiPlayer: "Multi Joueur",
    isFourPlayer: "2 contre 2",
    start: "Commencer",
    restart: "Recommencer",
    settingsBtn: "Paramètres",
    offcanvasHeader: "Menu",
    statisticsBtn: "Statistiques",
    tournamentBtn: "Tournoi",
    historyBtn: "Historique",
    modalSettings: "Paramètres",
    ballHeader: "Balle",
    "speed-ball": "Vitesse",
    "acceleration-ball": "Accélération",
    AI: "IA",
    "difficulty-ai": "Difficulté",
    language: "Langue",
    "language-choice": "Choix de la langue",
    "validate-btn-Stgs": "Enregistre les choix",
    "input-Username": "Choisit les noms pour les joueurs",
    "input-Username-Finish": "Tous les joueurs ont été nommés",
    "title-tournament": "Créer Un Tournoi",
    "input-username-btn": "Enregistrer le choix",
    "start-tournament": "Commencer le tournoi",
    loginModal: "Connecter",
    loginHeader: "Connecter",
    password: "Mot de passe",
    login: "Nom d'utilisateur",
    "validate-btn-login": "Enregistre les choix",
    "nbr-player-tournament": "Choisit combien de joueurs",
    "defaultValue-nbrPlayer": "Valeur par défaut est 4",
    "create-Tournament1": "Tournoi",
    "2modal-BackBtn" : "Retour",
    "tournament-panel": "Tournoi",
    "round-display": "Tour",
    "order-playing": "Ordre des matchs",
    "winnerTournament" : "Le champion est ",
    "finishTournament" : "Terminer",
    "registerHeader": "Inscription",
    "confpassword": "Confirmation",
    "login-registe" : "Nom d'utilisateur",
    "validate-btn-register" : "Enregistre les choix",
    "registerModalBtn" : "Inscription",
    "textSize": "Grosseur de text",
    "text-Size": "Choisit la grosseur",
    "sizes": "Petit",
    "sizem": "Moyen",
    "sizel": "Gros",
    "sizexl": "Très gros",
    "modalStatistics": "HISTOIRE",
    "modalStatistic": "HISTOIRE",
    "nbrPlayer-Btn" : "Suivant",
    "logoutModal" : "Déconnexion",
    "profileModalLabel" : "PROFILE",
    "emailR" : "E-Mail",
    "login-change" : "Enregistre les choix",
    "regist-changes" : "Enregistre les choix",
    "stat-mode": "Mode",
    "stat-vict": "Victoire",
    "stat-def": "Défaite",
    "stat-total": "Total",
    "stat-single": "Joueur solo",
    "stat-multi": "Joueur multi",
    "stat-2v2": "2 contre 2",
    "stat-tourn": "Tournoi",
    "hist-mode": "Mode de jeu",
    "hist-date": "Date",
    "registerModalLabel": "S'INSCRIRE",
    "start-login": "Nom d'utilisateur",
    "start-password": "Mot de passe",
    "start-confpw": "Confirmer le mot de passe",
    "start-mail": "E-mail",
    "register-save-btn": "Valider",
    "exampleModalLabel": "CONNEXION",
    "login-start": "Identifiant",
    "pw-start": "Mot de passe",
    "reset-password-link": "Mot de passe oublié ?",
    "validate-btn-login": "Se connecter",
    "command-ModalLabel": "COMMANDES DU JEU",
    "gctrl-single": "Joueur Unique",
    "gctrl-splayer": "Joueur",
    "gctrl-skey": "Touche",
    "gctrl-saction": "Action",
    "gctrl-splayer1": "Joueur 1",
    "gctrl-sw": "W",
    "gctrl-swmoveup": "Monter",
    "gctrl-ss": "S",
    "gctrl-smoveDown": "Descendre",
    "gctrl-multi": "Multijoueur",
    "gctrl-mplayer": "Joueur",
    "gctrl-mkey": "Touche",
    "gctrl-maction": "Action",
    "gctrl-mplayer1": "Joueur 1",
    "gctrl-mw": "W",
    "gctrl-mwmoveup": "Monter",
    "gctrl-ms": "S",
    "gctrl-mmoveDown": "Descendre",
    "gctrl-mplayer2": "Joueur 2",
    "gctrl-marrup": "Flèche Haut",
    "gctrl-mmoveup": "Monter",
    "gctrl-marrdown": "Flèche Bas",
    "gctrl-mmovedown": "Descendre",
    "gctrl-2v2": "2 contre 2",
    "gctrl-2team1": "Équipe 1",
    "gctrl-2player": "Joueur",
    "gctrl-2key": "Touche",
    "gctrl-2action": "Action",
    "gctrl-2player1": "Joueur 1",
    "gctrl-2w": "W",
    "gctrl-2moveup": "Monter",
    "gctrl-2s": "S",
    "gctrl-2movedown": "Descendre",
    "gctrl-2player2": "Joueur 2",
    "gctrl-2arrup": "Flèche Haut",
    "gctrl-2moveup2": "Monter",
    "gctrl-2arrdown": "Flèche Bas",
    "gctrl-2movedown2": "Descendre",
    "gctrl-2team1": "Équipe 2",
    "gctrl-2Tplayer": "Joueur",
    "gctrl-2Tkey": "Touche",
    "gctrl-2Taction": "Action",
    "gctrl-2Tplayer3": "Joueur 3",
    "gctrl-2Tn": "N",
    "gctrl-2Tmoveup": "Monter",
    "gctrl-2Tm": "M",
    "gctrl-2Tmovedown": "Descendre",
    "gctrl-2Tplayer4": "Joueur 4",
    "gctrl-2T2": "2",
    "gctrl-2Tmoveup2": "Monter",
    "gctrl-2T3": "3",
    "gctrl-2Tmovedown2": "Descendre",
    "gctrl-tournament": "Tournoi",
    "gctrl-tplayer": "Joueur",
    "gctrl-tkey": "Touche",
    "gctrl-taction": "Action",
    "gctrl-tplayer1": "Joueur 1",
    "gctrl-tw": "W",
    "gctrl-tmoveup2": "Monter",
    "gctrl-ts": "S",
    "gctrl-tmovedown": "Descendre",
    "gctrl-tplayer2": "Joueur 2",
    "gctrl-tarrup": "Flèche Haut",
    "gctrl-tmoveup": "Monter",
    "gctrl-tarrdown2": "Flèche Bas",
    "gctrl-tmovedown2": "Descendre",
    "enter-friend-name": "Entrer le nom",
    "add-friend": "Ajouter un ami",
    "login-profile": "Connexion",
    "friend-name": "Nom de l'ami",
    "online-stat": "Statut en ligne",
    "game-stat": "Statut du jeu",
    "save-changes-profile": "Enregistrer les modifications",
    "delete-profile": "Supprimer le profil",
    "nbr-ball": "Nombre",
    "hist-result": "Résultat",
    "hist-time": "Temps",
    "general-conditions-link1": "Conditions générales",
    "general-conditions-link2": "J'accepte les termes et conditions",
    "codeInput": "Entrez le code à 6 chiffres envoyé à votre e-mail",
    "twofactor": "Authentification à deux facteurs",
    "validate-otp-btn": "Valider OTP",
    "otp-input": "Entrez votre OTP"
    
    
},
jp: {
    singlePlayer: "シングルプレイヤー",
    multiPlayer: "マルチプレイヤー",
    isFourPlayer: "2対2",
    start: "スタート",
    restart: "リスタート",
    settingsBtn: "設定",
    offcanvasHeader: "メニュー",
    statisticsBtn: "統計",
    tournamentBtn: "トーナメント",
    historyBtn: "履歴",
    modalSettings: "設定",
    ballHeader: "ボール",
    "speed-ball": "速度",
    "acceleration-ball": "加速度",
    AI: "AI",
    "difficulty-ai": "難易度",
    language: "言語",
    "language-choice": "言語を選択",
    "stat-tourn": "トーナメント",
    loginModal: "ログイン",
    loginHeader: "ログイン",
    password: "パスワード",
    login: "ログイン",
    "validate-btn-login": "選択を保存",
    "nbr-player-tournament": "プレイヤー数を選択",
    "defaultValue-nbrPlayer": "デフォルト値は4です",
    "create-Tournament1": "トーナメント",
    "2modal-BackBtn": "戻る",
    "tournament-panel": "トーナメント",
    "round-display": "ラウンド",
    "order-playing": "試合順",
    "winnerTournament": "チャンピオンは ",
    "finishTournament" : "フィニッシュ",
    "registerHeader": "登録",
    "confpassword": "パスワード確認",
    "login-registe": "ユーザー名",
    "validate-btn-register": "選択を保存",
    "registerModalBtn": "登録",
    "textSize": "テキストサイズ",
    "text-Size": "サイズを選ぶ",
    "sizes": "小さい",
    "sizem": "普通",
    "sizel": "大きい",
    "sizexl": "とくだい",
    "modalStatistics": "歴史",
    "modalStatistic": "歴史",
    "nbrPlayer-Btn" : "次",
    "logoutModal" : "ログアウト",
    "profileModalLabel" : "プロフィール",
    "emailR" : "メール",
    "login-change" : "選択を保存",
    "regist-changes" : "選択を保存",
    "stat-mode": "モード",
    "stat-vict": "勝利",
    "stat-def": "敗北",
    "stat-total": "合計",
    "stat-single": "シングルプレイヤー",
    "stat-multi": "マルチプレイヤー",
    "stat-2v2": "2対2",
    "stat-tourn": "トーナメント",
    "hist-mode": "ゲームモード",
    "hist-date": "日付",
    "registerModalLabel": "登録",
    "start-login": "ログイン",
    "start-password": "パスワード",
    "start-confpw": "パスワード確認",
    "start-mail": "Eメール",
    "register-save-btn": "登録",
    "exampleModalLabel": "ログイン",
    "login-start": "ログイン",
    "pw-start": "パスワード",
    "reset-password-link": "パスワードを忘れましたか？",
    "validate-btn-login": "ログイン",
    "validate-btn-Stgs": "選択を保存",
    "command-ModalLabel": "ゲームコントロール",
    "gctrl-single": "シングルプレイヤー",
    "gctrl-splayer": "プレイヤー",
    "gctrl-skey": "キー",
    "gctrl-saction": "アクション",
    "gctrl-splayer1": "プレイヤー1",
    "gctrl-sw": "W",
    "gctrl-swmoveup": "上に移動",
    "gctrl-ss": "S",
    "gctrl-smoveDown": "下に移動",
    "gctrl-multi": "マルチプレイヤー",
    "gctrl-mplayer": "プレイヤー",
    "gctrl-mkey": "キー",
    "gctrl-maction": "アクション",
    "gctrl-mplayer1": "プレイヤー1",
    "gctrl-mw": "W",
    "gctrl-mwmoveup": "上に移動",
    "gctrl-ms": "S",
    "gctrl-mmoveDown": "下に移動",
    "gctrl-mplayer2": "プレイヤー2",
    "gctrl-marrup": "矢印上",
    "gctrl-mmoveup": "上に移動",
    "gctrl-marrdown": "矢印下",
    "gctrl-mmovedown": "下に移動",
    "gctrl-2v2": "2対2",
    "gctrl-2team1": "チーム1",
    "gctrl-2player": "プレイヤー",
    "gctrl-2key": "キー",
    "gctrl-2action": "アクション",
    "gctrl-2player1": "プレイヤー1",
    "gctrl-2w": "W",
    "gctrl-2moveup": "上に移動",
    "gctrl-2s": "S",
    "gctrl-2movedown": "下に移動",
    "gctrl-2player2": "プレイヤー2",
    "gctrl-2arrup": "矢印上",
    "gctrl-2moveup2": "上に移動",
    "gctrl-2arrdown": "矢印下",
    "gctrl-2movedown2": "下に移動",
    "gctrl-2team1": "チーム2",
    "gctrl-2Tplayer": "プレイヤー",
    "gctrl-2Tkey": "キー",
    "gctrl-2Taction": "アクション",
    "gctrl-2Tplayer3": "プレイヤー3",
    "gctrl-2Tn": "N",
    "gctrl-2Tmoveup": "上に移動",
    "gctrl-2Tm": "M",
    "gctrl-2Tmovedown": "下に移動",
    "gctrl-2Tplayer4": "プレイヤー4",
    "gctrl-2T2": "2",
    "gctrl-2Tmoveup2": "上に移動",
    "gctrl-2T3": "3",
    "gctrl-2Tmovedown2": "下に移動",
    "gctrl-tournament": "トーナメント",
    "gctrl-tplayer": "プレイヤー",
    "gctrl-tkey": "キー",
    "gctrl-taction": "アクション",
    "gctrl-tplayer1": "プレイヤー1",
    "gctrl-tw": "W",
    "gctrl-tmoveup2": "上に移動",
    "gctrl-ts": "S",
    "gctrl-tmovedown": "下に移動",
    "gctrl-tplayer2": "プレイヤー2",
    "gctrl-tarrup": "矢印上",
    "gctrl-tmoveup": "上に移動",
    "gctrl-tarrdown2": "矢印下",
    "gctrl-tmovedown2": "下に移動",
    "enter-friend-name": "名前を入力",
    "add-friend": "友達を追加",
    "login-profile": "ログイン",
    "friend-name": "友達の名前",
    "online-stat": "オンラインステータス",
    "game-stat": "ゲームステータス",
    "save-changes-profile": "変更を保存",
    "delete-profile": "プロフィールを削除",
    "nbr-ball": "数",
    "hist-result": "結果",
    "hist-time": "時間",
    "general-conditions-link1": "利用規約",
    "general-conditions-link2": "利用規約に同意します",
    "input-Username": "プレイヤーの名前を選んでください",
    "input-Username-Finish": "すべてのプレイヤーの名前が決まりました",
    "title-tournament": "トーナメントを作成",
    "input-username-btn": "保存",
    "start-tournament": "トーナメントを開始",
    "codeInput": "メールに送信された6桁のコードを入力してください",
    "twofactor": "二要素認証",
    "validate-otp-btn": "OTPを検証する",
    "otp-input": "OTPを入力してください"

}
};

function changeLanguageProcess(language) {
    const select = dictionary[language];

    Object.keys(select).forEach(id => {
        const element = document.getElementById(id);
        if (element) {
            element.textContent = select[id];
        }
        // const inputElement = document.getElementById("otp-input");
        // inputElement.placeholder = dictionary[language]["otp-input"];
    });
}

export function changeLanguage() {
    const iLanguage = document.getElementById('languageSelection').value
    switch (iLanguage) {
        case "1":
            changeLanguageProcess('en');
            break;
        case "2":
            changeLanguageProcess('fr');
            break;
        case "3":
            changeLanguageProcess('jp');
            break;
    }
}

